---
- name:  Configure webserver with nginx
  hosts:  webservers
  become: true
  vars:
    tls_dir:  /etc/nginx/ssl
    key_file: nginx.key
    cert_file: nginx.cert
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
   - name: Install nginx
     package:
       name: nginx
       update_cache:  true
   - name: install nginx config template
     template:
      src: nginx.conf.j2
      dest:  "{{ conf_file }}"
      mode: 0644
     notify:  restart nginx
   - name:  enable nginx configration
     file: 
      dest: /etc/nginx/sites-enabled/default
      src: /etc/nginx/sites-available/default
      state: link
   - name:  copy index.html
     template: 
      src: index.html.j2
      dest: /usr/share/nginx/html/index.html
      mode: 0644
  handlers: 
   - name:  restart nginx
     service:
      name: nginx
      state: restart